opam-version: "2.0"
maintainer: "Jane Street developers"
authors: ["Jane Street Group, LLC"]
homepage: "https://github.com/public-release-reloaded/ppx_typed_fields"
bug-reports: "https://github.com/public-release-reloaded/ppx_typed_fields/issues"
dev-repo: "git+https://github.com/public-release-reloaded/ppx_typed_fields.git#v0.18_preview.130.100+614+reloaded"
doc: "https://ocaml.janestreet.com/ocaml-core/latest/doc/ppx_typed_fields/index.html"
license: "MIT"
x-maintenance-intent: ["(latest)"]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.5.0"}
  "base" {>= "v0.18~" & < "v0.19~"}
  "ppx_base" {>= "v0.18~" & < "v0.19~"}
  "ppx_compare" {>= "v0.18~" & < "v0.19~"}
  "ppx_enumerate" {>= "v0.18~" & < "v0.19~"}
  "ppx_globalize" {>= "v0.18~" & < "v0.19~"}
  "ppx_hash" {>= "v0.18~" & < "v0.19~"}
  "ppx_pipebang" {>= "v0.18~" & < "v0.19~"}
  "ppx_sexp_conv" {>= "v0.18~" & < "v0.19~"}
  "ppx_sexp_message" {>= "v0.18~" & < "v0.19~"}
  "ppx_string" {>= "v0.18~" & < "v0.19~"}
  "ppx_template" {>= "v0.18~" & < "v0.19~"}
  "ppxlib_jane" {>= "v0.18~" & < "v0.19~"}
  "sexplib" {>= "v0.18~" & < "v0.19~"}
  "sexplib0" {>= "v0.18~" & < "v0.19~"}
  "univ_map" {>= "v0.18~" & < "v0.19~"}
  "dune" {>= "3.17.0"}
  "ppxlib" {>= "0.38.0"}
]
available: arch != "x86_32"
synopsis: "GADT-based field accessors and utilities"
description: "
Part of the Jane Street's PPX rewriters collection.
"
